---
- hosts: all
  become: true
  roles:
    - role: AnsibleShipyard.ansible-zookeeper
    - {
        role: "ansible-kafka",
        kafka_hosts_initial: ["localhost"],
        kafka_zookeeper_hosts_initial: ["localhost"],
        kafka_hosts: ["kafka.dev.sudostream.io"],
        kafka_zookeeper_hosts: ["kafka.dev.sudostream.io"],
        kafka_version: 0.10.1.1,
        kafka_scala_serverion: 2.11
    }
  tasks:
    - name: Create Apache Kafka input topic.
      shell: /usr/local/kafka/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic aeh-api-definitions

    - name: Create Apache Kafka output topic.
      shell: /usr/local/kafka/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic generated-test-script

    - name: Create Apache Kafka output topic.
      shell: /usr/local/kafka/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic test-results

